name: release

on:
  push:
    branches: [main]

jobs:
  release-on-push:
    runs-on: 'ubuntu-latest'
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        run: npm install

      - name: Prepare
        run: npm run dev:prepare

      - name: Release
        run: "${{ secrets.GITHUB_TOKEN }} npm run release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
