name: release

on:
  push:
    branches: [main]

jobs:
  release-on-push:
    runs-on: 'ubuntu-latest'
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install
        run: npm install

      - name: Prepare
        run: npm run dev:prepare

      - name: Release
        run: npm run release
